platform: linux

image_resource:
 type: docker-image
 source:
  repository: openjdk
  tag: '8-jdk'
  
inputs:
 - name: pal-tracker
 - name: version
 
outputs:
 - name: build-output
 
run: 
 path: bash
 args:
 - -exc
 - |
  cd pal-tracker
  ./gradlew -P version=$(cat ../version/number) clean build
  cp build/libs/pal-tracker-*.jar ../build-output